### ISSUE TITLE
Window cut off at edge of screen

### ISSUE THREAD

**Issue by agnoster** [brow/Sukhasana#3]
![screen shot 2015-03-09 at 15 08 21](https://cloud.githubusercontent.com/assets/15210/6556509/3c12c396-c66e-11e4-94e1-52cc8df7f99d.png)

Screen resolution: 1440x2560 (portrait)

Pop-up always appears on Display 1, even when clicking the menu item on Display 2 (same resolution/orientation)

**Comment by brow** [comment]
Heh. I hadn't tested the app on a machine with a reasonable number of status items. Is that Bartender?

I think the behavior on multiple displays is unrelated, so I broke that out into #4.

**Comment by brow** [comment]
The screen edge issue is fixed by f9341d1ac824da41d3174ae41906e0f8b87ee479. Thanks for the report!

**Comment by agnoster** [comment]
:+1:
