### ISSUE TITLE
Instructions for how to install

### ISSUE THREAD

**Issue by agnoster** [brow/Sukhasana#7]
I'd like to have Sukhasana run at startup, but manually firing up XCode and running it is a bit of a pain ;-)

**Comment by brow** [comment]
Good idea. Would you mind testing this for me?

```
git checkout makefile
make install
```

**Comment by agnoster** [comment]
It installs it in /Applications, but I can't seem to actually use it now - it crashes when I select a result (either by hitting "enter" or clicking the option). However, that seems to be true even with the Debug build off master.

I don't know enough Swift/Xcode to actually debug, but this is what I see when I run it through Xcode:
![screen shot 2015-03-20 at 10 50 16](https://cloud.githubusercontent.com/assets/15210/6749782/d4b5983e-cef3-11e4-81ac-e32cad778402.png)

**Comment by brow** [comment]
Oops, that's an unrelated crash issue. Fixed in [v1.1.1](https://github.com/brow/Sukhasana/releases/tag/v1.1.1).

I've merged to fix into the `makefile` branch. Care to pull and try `make install` again?

**Comment by agnoster** [comment]
Should the makefile actually do `carthage update --platform Mac`? Also it seems not to rebuild with the new code - it just does the cp -r without actually recompiling, so I had to manually `make clean`.

Otherwise it now works!

**Comment by brow** [comment]
> Should the makefile actually do carthage update --platform Mac?

Good catch. Added.

> Also it seems not to rebuild with the new code - it just does the cp -r without actually recompiling, so I had to manually make clean.

I added a tip to the README to run `make clean install` after a `git pull`.

Thanks for the testing!
